### ISSUE TITLE
Integration tests leak bhyve VMs

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#154]
On an illumos host:

1. `pfexec cargo test integration`
2. `ls /dev/vmm`

Expected: No VMs are present.
Observed: Three VMs outlive the integration test.

This is a test-only problem in the sense that in production, Propolis VMMs will run in zones that will get cleaned up on instance stop, which will reclaim those VMs' resources, and we don't do this in tests. This is a moderately serious issue for the tests, though, since this effectively limits the number of VMs they can create in a single test run (if they create too many VMs, the host will OOM and new VM creation calls will block waiting for more memory).

**Comment by jclulow** [comment]
Perhaps the CI job that runs the test should check for resources that have not been cleaned up, and fail if it finds any.  That is, https://github.com/oxidecomputer/propolis/blob/master/.github/buildomat/jobs/tests-run.sh

**Comment by gjcolombo** [comment]
That would be a lovely backstop to have once I have a tactical fix in place, since I'm sure I will break that fix several times while I work on refactoring the integration tests :)

(I do want to make sure the framework does the right thing so that `cargo test` works correctly outside the Buildomat environment, but I think having Buildomat additionally check for possible framework issues makes lots of sense.)

**Comment by gjcolombo** [comment]
As discussed in #166, this is a problem for PHD tests too, for the same reasons as in the integration tests. It's cleanest to resolve it via the illumos bug mentioned above. If this turns out to be a huge pain point in the meantime, it might be possible to work around it in PHD's fixtures (e.g. it's gross, but PHD could shell out to bhyvectl in its test cleanup fixture to clean up VMs that weren't present when the test setup fixture ran and so were probably added by the test).
