### ISSUE TITLE
Migration: creating a migration-target Crucible upstairs prevents (or may prevent) the source from pausing

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#155]
@jmpesp and I were discussing live migration earlier and suspect the existing Crucible activation protocol and Propolis migration logic will combine to prevent migration of an instance with a Crucible backend. The troublesome sequence of operations is as follows:

1. Propolis P1 starts Crucible upstairs C1 which activates against a Crucible downstairs
2. A migration saga begins; Nexus creates Propolis P2 with the same device definitions as P1
3. When handling the instance ensure request that (AIUI) precedes migration, P2 creates Crucible upstairs C2, which activates against the same downstairs as C1
4. Activation obsoletes prior activations, so C1 is no longer connected to the downstairs, and all reads/writes will pend unless and until C1 reconnects

Then, when migration starts,

5. P1 asks all its devices and backends to quiesce so migration can continue
6. C1 handles the quiesce request by waiting for all outstanding I/Os to drain
7. But the I/Os won't complete because C2's activation from step 3 has invalidated C1's activation
8. So C1 never quiesces, so the migration never proceeds. Oops.

Note that we haven't verified this empirically yet--this is just what we think will happen based on code inspection and our understanding of the components and processes involved.

There are a couple possible ways to fix this:

1. Split the "entity creation" and "entity start" phases of the Propolis entity lifecycle such that backends only talk to external services when they're *starting*, as opposed to doing so when they're *created*. This solves the problem by deferring C2's activation from step 3 to a post-migration "start the target's entities" step.
2. Change the Crucible pause/migration discipline so that the Crucible backend migrates its in-flight operations instead of draining them. This solves the problem by allowing C1 to quiesce with I/Os outstanding; C2 then has to complete these I/Os as part of migration.

@jmpesp and I were leaning toward the first solution in our discussion today. I think the second one might work in principle, but would leave it to the Crucible experts to decide whether this sort of backend migration is possible for Crucible specifically.

**Comment by leftwo** [comment]
(Hi, I'm on vacation this week, but thought i would add a comment anyway :)

I believe the initial design of storage migration was to be the #1 described above, the upstairs has a `connect to downstairs` phase, then an `activate` phase, and this `activation` was added for (in part) the purpose of migration.
There is also a `BlockOp::Deactivate` command that can be used when propolis wishes to cleanly disconnect an upstairs from its downstairs, though I'm not sure if this is available at the volume level.
 
For #2, it was planned to eventually handle inflight IO that crossed the boundary into the upstairs, but that work has not been started yet (nor have we really thought about how we will do it).

**Comment by leftwo** [comment]
Oh, and as many upstairs as desired can be in the `connect to downstairs` phase as desired, but only one upstairs can be active at a time.

**Comment by gjcolombo** [comment]
I've written a PHD test that I think can reproduce this by kicking off a bunch of I/O in the guest (use `dd` to write a giant file containing data from /dev/random) and then migrating. I observe that 

- The test times out
- Logs from the source Propolis show that it got stuck pausing the Crucible backend
- Logs from the Crucible downstairs processes show them invalidating the source Propolis's connection to activate the new one

I haven't examined the source Propolis more closely to make sure that it is, in fact, stuck trying to retire I/O, but the circumstantial evidence above seems pretty strong. (Note that migration works just fine if the guest is quiesced--the guest I/O seems to be required to get things to wedge, as expected.)

(On a second run of this test, the migration target failed to start--it appears to have a thread stuck in `CrucibleBackend::create`. I suspect this is a separate issue (which may not even be in Propolis) that we'll need to investigate further.)

**Comment by gjcolombo** [comment]
I've been working on this the last couple of days and have hit some friction that I'm still figuring out how to overcome. Here are some general notes so I don't forget anything. Comments welcome.

So far I've been trying to avoid any Crucible API changes and have just tried to defer the "create a volume and activate it" step of Crucible initialization so that it happens after the migration source has paused and sent its state to the target. This has turned out to be tricky for a few reasons:

1. Volume creation/activation can fail, but the propolis-server VM controller assumes that `Entity::start` calls are all infallible.
2. Block devices expect to get block and sector size information when they're initialized. Today, we have to at least call Crucible's `Volume::create` to get these. That call implicitly calls `Volume::activate`, so unless that changes, we can't do this until we're ready to start the target
3. Propolis-server's initialization logic assumes that it can call `CrucibleBackend::get_uuid` as soon as the backend is created. This, too, requires the backend to have called `Volume::construct`.

(1) is not too hard to fix; we just make `Entity::start` return a `Result` and fail VM start if any entity fails to start.

(2) isn't too terrible to fix, either, but requires more logical leaps. Neither of the block devices (NVMe or virtio-block) actually requires block/sector size information until vCPUs are running (at which point they might issue device commands that query that information). Because the VM controller guarantees that all entities get `start` calls before any vCPUs run, the backends should have all the necessary information by the time the devices actually need it, so we can just defer initializing it until the first time it's needed (wrapping the result in a `OnceCell` or somesuch so that the information only has to be fetched once).

(3) is more of a pain because the VM controller really wants the UUID before any vCPUs start (it uses it e.g. to create a map of volume UUIDs to Crucible backend entities for the disk snapshot command to use). We can kinda-sorta work around this by naively assuming that the UUID in the backend's original `VolumeConstructionRequest` is the one Crucible will yield later once the volume is created, but this kind of relying on implementation details is absolutely an API Crime and we need to do something better.

To really fix (3), we need to get rid of all the uses of `get_uuid` in propolis-server's `initialize_storage_devices` call. To do that, we need to (a) choose what to name the Crucible backend entities and (b) figure out how the snapshot endpoint will find the entities if it doesn't have a convenient map of them. (a) is not too hard; we could just base the entity names on the names in the instance spec. (b) is mildly trickier, but it might be doable if we start all the entities and then (prior to vCPUs running) rummage through the inventory looking for the Crucible backends (whose names we know thanks to (a)) and create the UUID-based lookup for them at that time (the map lives in the VM controller anyway so delaying its initialization should be broadly OK).

---

I have a change that takes all the shortcuts I just described and will test it out more tomorrow (current problem is some sync/async madness that I need to sort out: `Entity::start` is not called from an async context, but its callees expect to be called from within an active tokio runtime).

It is possible that this is All Too Much and that the correct fix is really to untangle things on the Crucible side as described in [crucible#440](https://github.com/oxidecomputer/crucible/issues/440), but I'll proceed with prototyping just to see if there are any other pitfalls I haven't found yet.

**Comment by gjcolombo** [comment]
The approach in the previous comment seems to work, at least insofar as the following test passes:

1. Start migration source
2. Generate a file with 100 MiB of random data & hash it
3. Start a background copy of the generated file into another file
4. Migrate the instance while the copy is in progress
5. On the migration target, wait for the copy to finish and verify that the copied file has the same hash as the original

Without any changes, the migration attempt usually either hangs or causes NVMe commands to be dropped and to time out. With my prototype  changes, this test will pass (though it sometimes encounters some NVMe timeouts during step 2).
