### ISSUE TITLE
LM testing in CI requires `vmm_allow_state_writes` to be set on the host machine

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#183]
[This branch](https://github.com/oxidecomputer/propolis/tree/gjcolombo/phd-migration) adds live migration support and some test cases to PHD, but it [failed its Buildomat test run](https://github.com/oxidecomputer/propolis/runs/7635358819).

The migration target's VMM logs contain this message:

```
Aug 02 16:09:48.678 ERRO Migrate Task Failed: failed to migrate device state: failed to apply deserialized device state: Not owner (os error 1), migrate_src_addr: 127.0.0.1:9000, migrate_role: destination, migration_id: 433278b2-339f-4754-b654-caf73f97523b, uri: /instance, method: PUT, req_id: c2097787-1910-4ccf-b596-9cec4cc22ca9, remote_addr: 127.0.0.1:60585, local_addr: 127.0.0.1:9002
```

Migration currently requires the host OS's [`vmm_allow_state_writes`](https://src.illumos.org/source/xref/illumos-gate/usr/src/uts/intel/io/vmm/vmm_sol_dev.c?r=54cf5b63&mo=2338&fi=85#85) switch to be set, which currently requires manual intervention. To unblock LM testing, we need to either:

- So intervene on the relevant test machine(s)
- Teach PHD to intervene automatically (and undo its handiwork when tests are finished)
- Change the required host OS bits to an (as yet hypothetical) version that allows state writes by default

**Comment by jclulow** [comment]
If you want to set a kernel variable, you might consider:

* `/dev/ksyms` (see [ksyms(4D)](https://illumos.org/man/4D/ksyms)) exposes the kernel memory location of various symbols as a virtual ELF file
* `/dev/kmem` (see [kmem(4D)](https://illumos.org/man/4D/kmem)) exposes as a read/write device the kernel address space
* [libkvm(3LIB)](https://illumos.org/man/3LIB/libkvm) ties this all together and could be used from Rust pretty easily; [kvm_open(3KVM)](https://illumos.org/man/3KVM/kvm_open), [kvm_nlist(3KVM)](https://illumos.org/man/3KVM/kvm_nlist), and [kvm_kwrite(3KVM)](https://illumos.org/man/3KVM/kvm_kwrite) your way to success!

**Comment by gjcolombo** [comment]
Coooool. I'll give this a try when I loop back around to the draft change. Thanks for the suggestions!

**Comment by gjcolombo** [comment]
:tada: 

https://github.com/oxidecomputer/propolis/runs/7774762341; see also [the logs](https://buildomat.eng.oxide.computer/wg/0/details/01GA4MZK51E9XGV7EDRPPYRQT9/NYSe508hRk3RW6W4rMh2LdVCdHVxMJQH8YtBGUlvuZ0FqVwV/01GA4N015MD8BYXSY35MHNJACM) from lines 769-783.

libkvm worked great for this. I've pushed the changes to the phd-migration branch and will close this issue when that merges. Thanks again for the pointers, @jclulow!
