### ISSUE TITLE
Instances lose network connectivity after migrating

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#200]
Repro steps:

1. Create a simple VM config; here I've used a Debian 11 nocloud image and saved the TOML to `debian11.toml`:

```
bootrom = "/home/greg/vm/OVMF_CODE.fd"

[block_dev.debian11]
type = "file"
path = "/home/greg/vm/debian11/debian-11-nocloud-amd64-20220711-1073.raw"

[dev.block0]
driver = "pci-nvme"
block_dev = "debian11"
pci-path = "0.4.0"

[dev.net0]
driver = "pci-virtio-viona"
vnic = "vnic_prop0"
pci-path = "0.5.0"
```

Then, from a couple of terminals in a directory containing Propolis binaries:

2. `pfexec ./propolis-server run /path/to/debian11.toml 127.0.0.1:12400 127.0.0.1:5900`
3. `pfexec ./propolis-server run /path/to/debian11.toml 127.0.0.1:12401 127.0.0.1:5901`
4. `./propolis-cli --server 127.0.0.1 -p 12400 new -m 1024 myvm && ./propolis-cli --server 127.0.0.1 -p 12400 state run`
5. `./propolis-cli --server 127.0.0.1 -p 12400 serial`
6. Log into the instance; observe that it has outbound network connectivity and that the VM host can ping it
7. Migrate the instance: `./propolis-cli -s 127.0.0.1 -p 12400 migrate 127.0.0.1 -p 12401 && ./propolis-cli -s 127.0.0.1 -p 12401 state run`. Migration may fail due to #184; unfortunately there's no recourse here but to stop the servers, go back to step 2, and try again.
8.  `./propolis-cli --server 127.0.0.1 -p 12401 serial`

Expected: The instance still has network connectivity.
Observed: Ping to/from the instance no longer works.

Additional notes:
- This happens even if the source and target have different host vNICs (note that some minor changes to the propolis-server instance spec code are needed to support this).
- This happens with both Helios and Debian 11 guests.

**Comment by gjcolombo** [comment]
I played around with this a little more. Running `snoop` on the assigned vNIC after migration shows a lot of output of the form

```
debian.home -> (broadcast)  ARP C Who is 192.168.254.254, gateway.home ?
gateway.home -> debian.home  ARP R 192.168.254.254, gateway.home is xx:xx:xx:xx:xx:xx
```

In the guest, `tcpdump` shows the ARP who-has requests being broadcast, but doesn't show any replies being received.

If I try to ping the instance from the host, I likewise see a lot of "who is <guest IP>" ARP traffic originating from the host, but no replies are received (and--I need to rerun this, but IIRC--tcpdump in the guest doesn't show anything arriving for it to respond to).

This all makes me vaguely suspect that something's up with the receive path in particular, but I still have more digging to do.

**Comment by pfmooney** [comment]
> This happens even if the source and target have different host vNICs (note that some minor changes to the propolis-server instance spec code are needed to support this).

How did you configure the vnics when you attempted that?

Considering that when using the same vnic for both instances, the viona driver likely attaches its MAC client upon initialization, which may complicate matters.  Testing migration with a working (able to send traffic via the same underlying NIC) guest NIC on the same machine might be a challenge. (At least without some rework to how we expect viona to attach/detach from a NIC)

**Comment by gjcolombo** [comment]
In the tests I did yesterday, the source and target specified the same vNIC. In the test where they had distinct vNICs (which I haven't rerun yet, but can try), the two vNICs had distinct MAC addresses (different values passed to the `-m` parameter of `dladm create-vnic`) but were bound to the same physical link on their shared host machine.

**Comment by gjcolombo** [comment]
We discussed this offline and concluded that the setup I was using (intra-machine migration using a single physical link) is not supported and not currently in scope for us (we don't have immediate plans to support intra-machine migration in the first place).

It turns out that the test machine I'm using supports two physical links; if I set things up so that each link has one vNIC and the two vNICs have the same MAC address, then connectivity survives a migration.
