### ISSUE TITLE
Consider adding "failed" terminal VM state

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#209]
Follow-up from the review of #208.

Fatal errors that are handled on the state worker (e.g. faults from a vCPU that halt the VM, errors from vCPU run ioctls) currently panic the host process. Instead, they could move the VM into a "faulted" terminal state, after which the server would wait for further instructions.

This would allow the VM owner or an operator to examine the VM and its state to try to diagnose the fault, though this would come at the cost of the resources needed to preserve the VM and any of its state while the VM is in the failed state.

Even if we don't want to keep that data, reporting guest-driven faults in an orderly manner will let us (or an operator) distinguish more clearly between, say, an assertion failure in Propolis (implying a code bug in the VMM) from an unrecoverable guest fault (possibly, albeit not absolutely, a problem with guest software).

**Comment by luqmana** [comment]
So we do already have such a state in the API:

https://github.com/oxidecomputer/propolis/blob/9ee3e5657437f3c1cf2c4df9c7b48bc81e5b9b7f/lib/propolis-client/src/handmade/api.rs#L139

We just don't make use of it yet.
