### ISSUE TITLE
server: users of `instance_get` can't guarantee that an instance's bhyve VM is destroyed

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#270]
When the server creates a VM controller, the controller creates a task that sends "instance stopped" notifications back to the upper layers of the server: https://github.com/oxidecomputer/propolis/blob/5ea6e6fd86bedce9a6a18f1f1b339550cbba5f60/bin/propolis-server/src/lib/vm.rs#L572-L584

This unwinds back to a call to `ServiceProviders::stop`, which tears down all of the upper-layer objects that the server manages: https://github.com/oxidecomputer/propolis/blob/5ea6e6fd86bedce9a6a18f1f1b339550cbba5f60/bin/propolis-server/src/lib/server.rs#L182-L192

The call to `take_controller` on line 186 changes the server's VM state to a "Destroyed" variant as follows: https://github.com/oxidecomputer/propolis/blob/5ea6e6fd86bedce9a6a18f1f1b339550cbba5f60/bin/propolis-server/src/lib/server.rs#L121-L143

Notice that lines 125 and 137 immediately change the server's externally-presented VM state to `InstanceState::Destroyed` even though the `Arc<VmController>` is still active. This creates a window in which `instance_get` will return `Destroyed` even though the underlying controller (and the instance and bhyve VMM to which it holds references) still has at least one active reference.

This currently causes flakiness in CI: PHD wants to make sure a test VM's bhyve handles are torn down before destroying any Propolis servers; to do that, it waits for Propolis to return the `Destroyed` state from a `get` call; but the race above means that `Destroyed` doesn't imply that the underlying VM is gone.

**Comment by luqmana** [comment]
Right, I had put up one approach to fixing this in https://github.com/oxidecomputer/propolis/pull/251 Though, wanted to explore other avenues but unfortunately got on the backburner.

**Comment by gjcolombo** [comment]
Yeah, this is everyone's favorite test flake :| Just realized I hadn't filed anything for it and wanted to get something on the tracker.
