### ISSUE TITLE
Long-running Crucible backend pause (73 secs) caused an instance stop timeout in Omicron CI

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#302]
Buildomat run: https://buildomat.eng.oxide.computer/wg/0/details/01GQ4HFTKKHENH6JTMQ0SN3XQ7/kGycG4YTJklIIrfJXZ5tTxRq199XXVSMydiGwb1261i2DDvJ/01GQ4HG357ZJBJCET0KSQQCC2T#S390

In the run logs we have:

```
363 | 2023-01-19T08:43:48.321Z | running 1 test
364 | 2023-01-19T08:43:49.759Z | Jan 19 08:44:18 sock xde: WARNING: disabling overlay for port: opte0
365 | 2023-01-19T08:44:48.306Z | test instance_launch::instance_launch has been running for over 60 seconds
366 | 2023-01-19T08:47:44.893Z | Error: timed out after 60.668695496s
```

In the sled agent logs we see that at the point where the timeout occurs, we're waiting for Propolis to process a stop request:

```
438 | 2023-01-19T08:47:13.278Z | INFO | SledAgent (InstanceManager): Taking action: Stop     instance_id = 016a2333-c560-47e2-9939-0ade31581c39
439 | 2023-01-19T08:47:13.279Z | INFO | SledAgent (dropshot (SledAgent)): request completed     local_addr = [fd00:1122:3344:101::1]:12345     method = PUT     remote_addr = [fd00:1122:3344:101::3]:50770     req_id = 55fd6983-3490-4a38-8df2-6f1b23115d11     response_code = 200     uri = /instances/016a2333-c560-47e2-9939-0ade31581c39
440 | 2023-01-19T08:47:13.279Z | INFO | SledAgent (InstanceManager): Observing new propolis state: Stopping     instance_id = 016a2333-c560-47e2-9939-0ade31581c39
441 | 2023-01-19T08:47:13.279Z | INFO | SledAgent (InstanceManager): New state: Stopping, action: None     instance_id = 016a2333-c560-47e2-9939-0ade31581c39
// N.B. 73 seconds elapse
442 | 2023-01-19T08:48:26.195Z | INFO | SledAgent (InstanceManager): Observing new propolis state: Stopped     instance_id = 016a2333-c560-47e2-9939-0ade31581c39
443 | 2023-01-19T08:48:26.195Z | INFO | SledAgent (InstanceManager): New state: Stopped, action: None     instance_id = 016a2333-c560-47e2-9939-0ade31581c39
```

Omicron just picked up a new Propolis package containing the fix for #283, so this is probably some entity taking its time pausing. Unfortunately we don't appear to have Propolis logs from this run, so we can only guess which entity it is (or we can just inspect them to look for things that can run long; there aren't really that many pause implementations).

(For what it's worth, in #283 I declined to add a `PauseReason` enum on YAGNI grounds. It might be that we did, in fact, need it, or at least would have benefited here from letting entities distinguish "you are being paused so I can migrate you" from "you are being paused because the VM is stopping.")

**Comment by gjcolombo** [comment]
@iliana [tweaked this test](https://github.com/oxidecomputer/omicron/commit/1f0f3a226f3fffdfe01a5c914020ee9c14634e83) (many thanks!) to make it possible to extract some [Propolis server logs](https://buildomat.eng.oxide.computer/wg/0/artefact/01GQ5KVSZ0RS4VWQH8XB8Z5VC9/yYbRRBMDQ4noJLmgXpwYpxIXBlu3MuMU4nlkGoS1VPhQlSar/01GQ5NN6BQ240857E79CXAC5VY/01GQ5P50F1FMMT3M72RF9YCN1B/system-illumos-propolis-server:vm-de429f57-d8b5-4dea-85b6-32ef72b3b881.log) from it. These end with the following:

```
Jan 19 18:56:46.364 INFO Stopping instance, component: vm_state_worker
Jan 19 18:56:46.364 INFO vCPU paused, vcpu: 0, component: vcpu_tasks
Jan 19 18:56:46.364 INFO request completed, response_code: 200, uri: /instance/state-monitor, method: GET, req_id: b8ada767-336d-4d9b-9604-fa39e413d658, remote_addr: [fd00:1122:3344:101::1]:59984, local_addr: [fd00:1122:3344:101::12]:12400
Jan 19 18:56:46.364 INFO vCPU paused, vcpu: 1, component: vcpu_tasks

// various chipset devices pause...

Jan 19 18:56:46.365 INFO Sending pause request to pci-virtio-viona-0.8.0, component: vm_controller
Jan 19 18:56:46.365 INFO Sending pause request to pci-nvme-0.16.0, component: vm_controller
Jan 19 18:56:46.365 INFO Sending pause request to block-crucible-6b39f646-4453-4f10-b389-79c9d85a88f4, component: vm_controller
```

Note the absence of a "waiting for entities" log line: https://github.com/oxidecomputer/propolis/blob/994f40f196c0a6ebfdd6520bfc1373cc52ba1776/bin/propolis-server/src/lib/vm/mod.rs#L1156-L1164

This peels the onion somewhat: the Crucible backend's `pause` callout just pauses its `block::Scheduler`, and that waits synchronously for the scheduler's request-posting thread to report that it's halted, which requires the scheduler's active request count to hit zero: https://github.com/oxidecomputer/propolis/blob/994f40f196c0a6ebfdd6520bfc1373cc52ba1776/lib/propolis/src/block/mod.rs#L855-L870

So the next question is what's holding things up in the Crucible backend (or the Crucible upstairs that's implementing the block I/O trait for it). I'm not sure we have enough logging in place to answer that question, though (there's nothing I can see in the Propolis logs, at any rate); we might have to reproduce this and enable some extra tracing to get more data on what's happening.

**Comment by leftwo** [comment]
I'm little confused as to what the pause here is pausing?  There is not a "pause" command that exists in crucible, so is this pausing the scheduler that the crucible tasks are running on?

**Comment by leftwo** [comment]
Do we also know the exact pause time that `pause` on `block::Scheduler` was?  I think the entire test took 73 seconds to finish, which was more than the 60 second limit, but we don't have timings for the whole test, do we?

**Comment by gjcolombo** [comment]
> I'm little confused as to what the pause here is pausing? There is not a "pause" command that exists in crucible, so is this pausing the scheduler that the crucible tasks are running on?

Yes, that's correct (specifically we're calling `propolis::block::crucible::CrucibleBackend::pause`, which just pauses the task scheduler that relays requests from disk devices to backend's Crucible upstairs).

> Do we also know the exact pause time that pause on block::Scheduler was? I think the entire test took 73 seconds to finish, which was more than the 60 second limit, but we don't have timings for the whole test, do we?

I don't think we know exactly. The 73-second interval was drawn from a different test run than the one with actual Propolis logs. (To be fair, I'm assuming/inferring from the circumstances that the two failed runs have the same root cause; it could be that a different entity got stuck in the run where we don't have Propolis logs than in the run where we do; but to find that out I think we'll want to get past the bug that's visible in the we-have-logs case.)

The sequence of events in the "stop took 73 seconds" run is

1. Buildomat starts the test; I assume the test creates, starts, and stops an instance and waits at each step for the right instance states to become visible
2. The test asks the instance to stop
3. Before the "stopped" state becomes visible, a 60-second per-test timeout elapses, causing the test to fail
4. Buildomat begins collecting a bunch of diagnostic information from the system and the Omicron zones
5. While Buildomat is doing that, Propolis finally stops and sled agent observes the transition
6. Sled agent tears down the Propolis zone (it does this automatically when an instance is destroyed)
7. Eventually a Buildomat command to gather diagnostics from the Propolis zone fails
8. Buildomat uploads the sled-agent log containing all the history from steps 2-6, which lets us infer that there was a 73-second delay stopping the instance

Since the Propolis zone was torn down before Buildomat gathered its logs, we don't know what exactly Propolis was doing during the slow stopping -> stopped transition; we only know how long it took from what sled agent logged.

In the test run with Propolis logs, the instance times out while stopping, but the Buildomat job is configured to skip step 4, such that Propolis hasn't shut down by the time the job goes to extract logs from the Propolis server zone. Those logs show that the last thing Propolis did was to call `CrucibleBackend::pause`, but in this case the instance doesn't fully stop before Buildomat extracts the sled agent logs and ends the job, so we don't know how long it would have taken for the instance to stop if we'd let it go on trying.

**Comment by gjcolombo** [comment]
Worth noting: during these runs, there was a lab networking issue that appears to have... materially decreased the performance and reliability of connections to the lab server that serves our test disk images. I *think* that server is acting as a read-only parent here. If that's so, this isn't necessarily a Crucible logic bug--it's more that Crucible had to go out to the network to get some blocks and found that that was terribly slow.

**Comment by iliana** [comment]
> I _think_ that server is the host of this VM's disk's read-only parent volume here.

This is correct.

**Comment by gjcolombo** [comment]
Anecdata from team chat suggests that CI flakiness due to slow connections to the image server is now less of a problem. Since that was the most probable cause of this issue, closing this for now.
