### ISSUE TITLE
Fail & destroy the VM controller when migration in fails

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#323]
Today, a migration target remains in the "Migrating" state when a migration in fails, and has a lifecycle stage that prevents a subsequent migration from being attempted with the same VM controller. VMs in this state should self-destruct instead.

This is required to handle cases where migration fails because the source crashed. In this case, Nexus needs to be able to figure out that the instance has failed. But it's unsafe for the target to tell Nexus this: if migration failed because the source/target connection was interrupted, but the source is otherwise alive, then the instance is still running. So the safest course is just to terminate the target: if the source is still alive, it will notice that migration failed and push an appropriate update to Nexus; if the source is gone, then neither the source nor the target will be responsive, and Nexus can observe this by checking both VMMs for a heartbeat.

**Comment by gjcolombo** [comment]
I... don't really understand what I had in mind when I wrote this issue up originally! My notes are also not much help.

I think the following statements are all true:

1. Propolis should do something other than getting stuck in the "migrating" state when a migration in fails.
2. That something could be "exit the VM state driver and tear down the instance."
3. When migration into a target fails, the target doesn't know whether the VM is running or not (maybe the source is still alive and resumed the VM, or maybe not), so it (or, more precisely, its sled agent) has to be careful not to represent to Nexus that the instance is in any particular state.

But I don't think (3) *requires* (2). It would also be legitimate to mark the VM as failed and *not* destroy it until sled agent asks it to stop. Either way, sled agent will have to be conservative about what it reports to Nexus if it sees that a migration target's migration in failed.

Will use this bug to track the work to move out of the migrating state on a failed migration in.

**Comment by jordanhendricks** [comment]
Something I've had on my list of "live migration paper cuts" for awhile is that failed migrations can end up leaving lingering a /dev/vmm instance. It sounds like this issue will handle that?

**Comment by gjcolombo** [comment]
I expect so. The bhyve VMM goes away when its Propolis `Instance` goes away, which happens when the instance's VM controller gets dropped, which happens (roughly) when the VM's state driver exits and signals the overarching server that the instance should be destroyed.

Today, if you fail to migrate in, the state driver hangs around, but will exit if someone asks to stop the instance, which should clean everything up. (PHD exercises this implicitly in its tests for failed migration.) Once #346 merges, failing to migrate in will cause the state driver to push the instance to "Failed" and then return immediately, which starts the cleanup sequence with no further user intervention.

> It would also be legitimate to mark the VM as failed and not destroy it until sled agent asks it to stop. Either way, sled agent will have to be conservative about what it reports to Nexus if it sees that a migration target's migration in failed.

Having now worked this out in sled agent, I've decided it's simplest just to have the Propolis self-destruct when this happens (and, again, to have sled agent be very careful about sending instance state updates from failed migration targets).
