### ISSUE TITLE
Stopping an instance with a Crucible disk doesn't tear down its VMM

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#380]
This only happens with Crucible disks, not with file-backed disks.

Based on some dtrace sleuthing, I suspect what's happening is that the async block backend has an extra `VmmHdl` reference running around, which is keeping the instance's `VmmHdl` undropped even when the instance gets dropped, which is keeping the bhyve VMM's fd open, which is enough to keep the VM from being destroyed until the Propolis process goes away.

Some quick-and-dirty println work suggests it's the `propolis::block::Inner` that's not getting torn down, but I'm still working out how all the block backend pieces are put together to try to figure out what's not getting released.

**Comment by gjcolombo** [comment]
To help chase this down, I cobbled together a wrapper around `Arc` that has USDT probes in its Clone and Drop impls. This shows that the `block::Inner` has 11 references:

- one for the Scheduler itself
- one for each of the two tasks created in `block::Inner::attach`
- one for each of the eight scheduler worker threads

But only 10 references get released on stop. The eleventh reference appears to be from the block device notifier that gets set at the end of `attach`. I think this is a circular reference: the block device owns a callback that has a strong reference to the `block::Inner`, and the `Inner` has a `OnceCell` with a strong reference to the block device.

Converting the notification callback's reference to a `Weak` seems to fix the issue. Will have a PR up shortly.

**Comment by pfmooney** [comment]
> To help chase this down, I cobbled together a wrapper around `Arc` that has USDT probes in its Clone and Drop impls. 

Good thinking. That seems pretty useful!

>  I think this is a circular reference

A silly mistake on my part.  Sorry.
