### ISSUE TITLE
crucible log messages can intersperse with propolis-server log messages

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/propolis#407]
We've seen that crucible log messages can intersperse with other messages in the server logs, resulting in the log being unreadable at times. The root of this problem is that crucible in propolis creates its own logger instead of inheriting one from propolis-server.

Fixing this will require some changes on the crucible side as well.

**Comment by leftwo** [comment]
On the crucible side: https://github.com/oxidecomputer/crucible/issues/735

**Comment by leftwo** [comment]
Crucible now takes a `Logger` from propolis and uses that instead of creating its own logger, this should remove the logs overwriting each other.

However, an additional tag should be added to the `Logger` that will indicate a log came from Crucible and not Propolis.

**Comment by gjcolombo** [comment]
> However, an additional tag should be added to the Logger that will indicate a log came from Crucible and not Propolis.

I think this is done already: https://github.com/oxidecomputer/propolis/blob/9d5a457483a94ab8d4194359f50a4f5c84ffeee5/bin/propolis-server/src/lib/initializer.rs#L324-L331

Looking at my logs from a recent PHD/Crucible run, I see that the Crucible upstairs log lines indeed have a "component" element that's set to `crucible-<disk ID>`. That's enough to do something like `looker -f ./crucible_boot_test.stdout.log -c 'r.component?.contains("crucible")'` to get just the Crucible log lines.

Unless we think more is needed here, this seems like it's ready to resolve.
