### ISSUE TITLE
serial console for a non-migrated instance observed to be stuck

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/propolis#409]
There have been reports of hung serial consoles on dogfood. Live migration is not available there yet, which rules out other recently observed console hangs post-migration.

I looked at one specific instance and found that crucible was in good health, which rules out failure modes from a stuck guest, such as what happened #336. Both the console and the CLI appeared to hang.

In the propolis log, we see a bunch of these messages, which suggest to me that something in the websocket chain died:

```
May 17 15:34:25.447 ERRO Error returned from handler: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }), upgrade: websocket, uri: /instance/serial?from_start=0, method: GET, req_id: 329c8941-9d25-4412-b8e0-d71ca0abd0bd, remote_addr: [fd00:1122:3344:10a::4]:55450, local_addr: [fd00:1122:3344:104::22]:12400


```

**Comment by jordanhendricks** [comment]
The instance is:
- oxz_propolis-server_b1cb331e-4d6b-4e29-8bcf-a58b573d117e in cubby 17 -- BRM42220006
- console view is https://venus.oxide-preview.com/projects/andy/instances/sue/serial-console

Note that dogfood is updated frequently, so these details may go out of date fast.

Propolis and nexus logs are at /net/catacomb/data/staff/core/rack2/propolis-409

**Comment by lifning** [comment]
reading through chatlogs from andy contemporary to the issue first being brought up, the console would stop being accessible after a great deal of output had been written to it. i started investigating from that angle, and found one bug, though i'm not sure if it is the same cause as what was encountered here as the instance is gone:

the propolis logs uploaded by jordan here show requests being made for `/v1/instances/sue/serial-console/stream?project=andy&from_start=0` -- emphasis on the `from_start=0` -- which leads me to believe that the issue might relate to a bug in the websocket's initial "catch-up" behavior upon connection, that can occur when a client explicitly requests history from before the most recent mebibyte of output after over 2 MiB has been output over the instance's lifespan.

propolis's history buffer keeps the first 1 MiB and the last 1 MiB of output, and a newly-connecting client can be sent *some amount* of context from this upon connecting (`propolis-cli` defaults to asking for the `?most_recent=16384`).

this catch-up is done by propolis-server repeatedly grabbing (up-to-)16KiB chunks starting from the requested offset up until the current time and sending them to the new websocket client, and then passing the connection over to the live event loop task for more byte-sized interactivity.

but we're not (yet) checking that it is even *possible* to stitch together the requested amount of history before we go on attempting to -- i've produced this behavior locally by letting the instance scream for a while and then `propolis-cli --server 127.0.0.1 serial --byte-offset=0`: 
```json
{"msg":"Error returned from handler: ExpiredRange { requested_from_start: 1048576, requested_from_end: 9153114, beginning_len: 1048576, rolling_len: 1048576, total_bytes: 10201690 }","v":0,"name":"propolis-server","level":50,"time":"2023-05-18T02:46:13.051963786Z","hostname":"solar-winds","pid":17560,"upgrade":"websocket","uri":"/instance/serial?from_start=0","method":"GET","req_id":"f2b6aa03-ed06-4694-bd98-fa1796ebd355","remote_addr":"127.0.0.1:40447","local_addr":"127.0.0.1:12400"}
```
(connections that don't supply a `from_start` still work)

the purely *correct* thing to do would be to more clearly error out if an unsatisfiable offset is requested, but considering the user/developer experience here, i believe the *right* thing to do here may be to either clamp the requested value to within the most recent 1 MiB when such an error occurs, or remove `from_start` from the websocket-streaming endpoint's accepted parameters entirely (but certainly not from the history endpoint that was specifically made for requesting early output ranges).

(if this was indeed the reason for the issue, it is likely unrelated to the lock-ups we've seen occasionally after migrations where even the instance itself stops being able to interact with the tty device.)

**Comment by lifning** [comment]
my next clue is that it *"hangs when there's a burst of output from the guest"* - with running `prtconf -v` on OmniOS given as an example. it may be possible that the websocket frames are getting too big in those moments, and possibly even when attempting to replay history? on my local (non-dogfood) setup i only see frames get up to the high 600s in byte length when doing this (or even for `tr \\0 a < /dev/zero`), but perhaps something else troublesome is happening to cause the connection to fail between propolis and nexus when bigger binary frames are sent (this would also track with the behavior described that the web console doesn't show output at all when connecting - the catch-up frames are 16KiB apiece). investigating that next.

**Comment by lifning** [comment]
running on the dogfood rack right now with an eye on `serial_uart_read` in dtrace, i haven't been able to get it to get stuck. new cli and web console both working fine[^1].

in times of high-volume output, i'm observing the byte counts in each `serial_uart_read` to be in the low 500's, and the buffer it's reading into on each iteration is 1024 bytes long[^2], so we're not running into anything there.

a thing to note is that this is an instance *alone on its sled* doing nothing but shovel bytes to its serial port as fast as it can. if the issue is impacted by having competition for local resources (e.g. propolis-server's serial task not being able to poll fast enough to keep up with the guest for some reason), i wouldn't be seeing it right now. i'll take a look from that angle next.

[^1]: albeit the latter's a bit jank because it's not 80x24 like it should be, and because it's generally a bit more sluggish than a native terminal emulator
[^2]: even if it were filling the buffer, it shouldn't be a failure -- it'd just incur more protocol overhead, with each fill being its own message.

**Comment by lifning** [comment]
As we haven't heard of this happening again for several months, I'm inclined to believe that https://github.com/oxidecomputer/console/pull/1501 may have fixed the issue as observed. (Please reopen if anyone sees it again!)
