### ISSUE TITLE
propolis-cli may have a cancel-unsafe `tokio::select!`

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/propolis#434]
This is a small followup from https://github.com/oxidecomputer/omicron/issues/3356. I think [`InstanceSerialConsoleHelper::recv()`](https://github.com/oxidecomputer/propolis/blob/54a1fc672ae38b77b7f9beeb0dad8afcb3095d5d/lib/propolis-client/src/lib.rs#L124) is not cancel safe: it could pull a value from its `ws_stream`; if it is then cancelled at a later `.await` point, that value will be lost. This method is used [in a select! arm in propolis-cli](https://github.com/oxidecomputer/propolis/blob/54a1fc672ae38b77b7f9beeb0dad8afcb3095d5d/bin/propolis-cli/src/main.rs#L386), and could trigger cancel-unsafety issues there.

**Comment by sunshowers** [comment]
I think we may need to separate out the cancel-safe part (receiving a message from stream) from the cancel-unsafe part (any await points that happen afterwards).

**Comment by sunshowers** [comment]
Working on this now, I think I have a solution.

**Comment by sunshowers** [comment]
Fixed by #435.
