### ISSUE TITLE
Windows Server 2022 guests don't seem to boot or have responsive serial consoles

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#463]
I tried this with both the "generic cloud" image on Catacomb and a local WS2022 disk image I had around. The images boot successfully and display the SAC channel on the serial console, but the console isn't responsive to user input. VNC also doesn't show anything interesting happening (just the OVMF logo). The machine BSODs if sent an NMI via the `inject-nmi` command, and the bluescreen text gets displayed to the SAC (and the BSOD is displayed on the VNC console), so I don't think the emulation or the serial device are totally wedged. It feels more like there's something keeping us from booting normally even though certain emulation functions work fine.

This repros at the following commits:

- 1598c84a7a9d7684ad14ecd4b83b581a3bc182a6 (from today)
- d9434e54f8695b2c0e2f4f47c98c11095479e0e1 (March 2023)
- 92508d573529a1ee50a9422fbca045a5e980a2b5 (January 2023; note that this requires a lot of hacking Cargo.tomls in local clones of omicron/crucible/dropshot/progenitor/typify to get everything to build)

We had Windows working in October 2022, so a commit from around there is worth trying next, though it will likely require some additional Cargo.toml trickery to build.

Possible confounders here:

- All these tests ran with relatively new helios/bhyve bits (i.e. I didn't bisect hypervisor versions)
- The images I tested with are very old (the one I generated for myself is well past its evaluation window right now). I was hoping that these images would at least boot and then complain about not being activated properly. Still, it might be worth trying to create a new image to see if it behaves any better.

**Comment by pfmooney** [comment]
@gjcolombo did some great work on this to narrow it down to issues with the clocksource chosen by Windows.  When run with a ROM with a table describing the HPET (similar to what's shipped in the ROM for c-bhyve), things ran fine.  I did some further tracing, and found issues with how the vRTC handles periodic interrupts.  That's written up in [illumos#16053](https://www.illumos.org/issues/16053).

**Comment by pfmooney** [comment]
With illumos 16053 integrated, this should be considered as addressed.
