### ISSUE TITLE
want support for hot replacing a Crucible downstairs

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#470]
This is a specific case of #205. We discussed it at the 20 April 2023 hypervisor huddle.

Crucible allows a faulted downstairs to be hot-replaced: https://github.com/oxidecomputer/crucible/blob/179e68b8718d24673893dac46a8ab4a9249ec318/upstairs/src/volume.rs#L815. Propolis needs a way to invoke this upstairs function when needed.

The general plan we discussed to wire this up to the control plane involved the following (with some additional details tentatively filled in by yours truly):

- Propolis server will have an "update Crucible downstairs" endpoint that takes a disk ID and a `VolumeConstructionRequest` (or similar, e.g. a new Crucible storage backend element from the instance spec module)
- When invoked, the endpoint takes a 'state change hold' on the current VM's controller that prevents certain state changes from occurring. The list of such changes is TBD; presumably we don't want to live migrate while a configuration change is in progress; is instance stop/reboot still allowed?
- Propolis server looks in the VM controller for
  - a storage backend in the instance description with the correct name (derived from the disk ID)
  - an entry in the disk-ID-to-Crucible-backend map with the correct disk ID
- If both of these exist, the server passes the old and new volume construction requests to the Crucible backend of interest
- The backend compares the requests to see which regions have one or more new addresses
- The backend issues the appropriate `replace_downstairs` calls and returns a result
- If the replacement succeeded, Propolis server updates the relevant instance spec element to reflect the changes that were applied
- Propolis API call returns

Details we need to clarify:

- What instance lifecycle operations are and aren't allowed while a downstairs replacement is in progress?
- What happens if a downstairs replacement request arrives when we're already doing something that's mutually exclusive with that replacement?
  - Queuing the request and completing it asynchronously is challenging because the replacement may happen in the context of a saga, and (IME) it's challenging for a saga to poll for the completion of a particular asynchronous operation.
- Along similar lines: are downstairs replacements fast enough that we can reasonably try to complete them synchronously? What happens if such a request times out?

**Comment by leftwo** [comment]
> Are downstairs replacements fast enough that we can reasonably try to complete them synchronously?

Yes and no.  The "replace a downstairs" interface is asynchronous.  You can wait and verify that the request
is valid from the upstairs and that it will now begin the replacement process internally, as that should happen
without much delay.  The total time of the replacement will be dependent on the size of the volume.

Once the upstairs has accepted a "replace a downstairs" operation, all future VCRs for this upstairs
should be using the new VCR with the replacement downstairs, even if the repair has not had time
to complete.

**Comment by gjcolombo** [comment]
Per today's storage huddle: there is still some work needed here to make sure that this mutation is properly synchronized against things like migration, but we'll use #205 to track that and close this since the Crucible downstairs replacement API is otherwise in place.
