### ISSUE TITLE
Want support for instances beyond 32 vcpu and 64 GiB of memory

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/propolis#474]
We capped instance size to 32 vcpus and 64 GiB as a precaution after hitting https://github.com/oxidecomputer/omicron/issues/3417 and https://github.com/oxidecomputer/omicron/issues/3286. At least one of our customers has expressed the need for larger instances - up to 64 vcpus and 128 GiB memory (ideally 256 GiB but less important) as they have bursty workloads (e.g. one performs a lot of preprocessing and caching at during application startup).

**Comment by pfmooney** [comment]
Along with some propolis-side changes, this will be addressed in the short term by oxidecomputer/stlouis#458

**Comment by pfmooney** [comment]
The propolis (and helios) side of this should be set for instance featuring up to 64 vCPUs.
