### ISSUE TITLE
errror on failure to `open` vmm controller fd could include more context

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/propolis#505]
In `create_vm`, the `open` for `/dev/vmmctl` simply returns the IO error on failure: https://github.com/oxidecomputer/propolis/blob/f9bff8368bf8625319a99d7c09d8aa09c112e0e5/lib/propolis/src/vmm/hdl.rs#L49

On machines in which SVM is disabled in the BIOS, this `open` call will fail, but the error message isn't super helpful (`error 2 file not found`).

This error message could at least include a bit more context about what happened.

**Comment by arjenroodselaar** [comment]
The error pops up before creating a VM, as part of the API version checks:
```
arjen@helios:~/propolis$ pfexec truss -t stat,open /home/arjen/propolis/target/debug/propolis-standalone /home/arjen/alpine-vm0.cfg
stat("/home/arjen/propolis/target/debug/propolis-standalone", 0xFFFFFC7FFFDF70F0) = 0
...
open("/dev/urandom", O_RDONLY|O_CLOEXEC)        = 4
/1:     open("/dev/dtrace/helper", O_RDWR|O_CLOEXEC)    = 3
/1:     open("/dev/vmmctl", O_WRONLY|O_EXCL|O_CLOEXEC)  Err#2 ENOENT
Error: API version checks

Caused by:
    No such file or directory (os error 2)
```
It's the same function being called, but at a different site: https://github.com/oxidecomputer/propolis/blob/f9bff8368bf8625319a99d7c09d8aa09c112e0e5/lib/propolis/src/vmm/mod.rs#L18
