### ISSUE TITLE
PHD: want support for migration between distinct Propolis binaries

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#528]
Today PHD requires its invoker to pass a path to a Propolis server binary on the command line. This binary is used to run all the Propolis servers under test. PHD should allow users to supply multiple Propolis server binaries, e.g. as artifacts, and then should allow individual tests to specify which binary to use (or binaries, if testing live migration).

**Comment by hawkw** [comment]
I think #609 fixes this!
