### ISSUE TITLE
log non-sensitive portions of Crucible VCRs when setting up a new Crucible backend

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#536]
Prior to #472, Propolis machine initialization would log Crucible VolumeConstructionRequests before initializing Crucible backends: https://github.com/oxidecomputer/propolis/blob/d17770bbb724d5c2907f95b318e050eb763deb56/bin/propolis-server/src/lib/initializer.rs#L309-L313

With #472, Propolis logs the entire generated instance spec (including backend data) at the beginning of machine initialization, but this intentionally avoids printing the VCR to keep from logging the encryption keys contained therein. This is generally righteous but makes it harder to determine which Crucible instances have backed a particular Propolis's disks.

Once a VCR is deserialized, someone (I vote for the Crucible backend creation routine itself) should log the non-sensitive contents thereof.

**Comment by leftwo** [comment]
I second that vote for crucible to log.

**Comment by gjcolombo** [comment]
Will be resolved in the Crucible upstairs. See oxidecomputer/crucible#971 and oxidecomputer/crucible#974.
