### ISSUE TITLE
Propolis returned 'Not found' after hitting "thread 'vcpu-7' panicked" error

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/propolis#543]
Nexus got a "Not Found" error from sled agent when it tried to do an instance PUT for a instance stop request. This is the error in sled-agent log:
```
19:10:05.452Z ERRO SledAgent (InstanceManager): Error from Propolis client: Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "ecfaa6e0-fe7a-4a77-830e-787bd3242298", "content-length": "84", "date": "Fri, 06 Oct 2023 19:10:05 GMT"}; value: Error { error_code: None, message: "Not Found", request_id: "ecfaa6e0-fe7a-4a77-830e-787bd3242298" }
    file = sled-agent/src/instance.rs:409
    instance_id = 7f189789-5745-4c97-933f-6ea61123fe51
    status = Some(404)
19:10:05.452Z INFO SledAgent (dropshot (SledAgent)): request completed
    error_message_external = Not Found
    error_message_internal = Not Found
    file = /home/build/.cargo/git/checkouts/dropshot-a4a923d29dccc492/4782435/dropshot/src/server.rs:841
    latency_us = 704
    local_addr = [fd00:1122:3344:10c::1]:12345
    method = PUT
    remote_addr = [fd00:1122:3344:111::3]:61186
    req_id = c836a146-4b0e-433c-ac05-b58093c7b068
    response_code = 404
    uri = /instances/7f189789-5745-4c97-933f-6ea61123fe51/state
```
And this is the error that induced a propolis panic, as seen in the propolis log:
```
{"msg":"Scrub at offset 2516736/6291456 sp:2516736","v":0,"name":"propolis-server","level":30,"time":"2023-10-06T15:14:32.345786415Z","hos
tname":"oxz_propolis-server_1df2e802-2b61-4ae2-9ddf-2199e0196363","pid":21926,"component":"crucible-7cf881cc-71cf-46c3-b17a-3e78de8bc33f"}
thread 'vcpu-7' panicked at '{"msg":"piix3pm ignored cfg read","v":0,"name":"propolis-server","level":30,"time":"2023-10-06T15:15:00.829605421Z","hostname":"oxz_propolis-server_1df2e802-2b61-4ae2-9ddf-2199e0196363","pid":21926,"dev":"chipset","register":"CountA","offset":0}
assertion failed: copy_len <= data_len.checked_sub(wr_off).unwrap()', {"msg":"piix3pm ignored cfg read","v":0,"name":"propolis-server","level":30,"time":"2023-10-06T15:15:00.829805009Z","hostname":"oxz_propolis-server_1df2e802-2b61-4ae2-9ddf-2199e0196363","pid":21926,"dev":"chipset","register":"CountB","offset":0}
lib/propolis/src/common.rs{"msg":"piix3pm ignored cfg read","v":0,"name":"propolis-server","level":30,"time":"2023-10-06T15:15:00.829830928Z","hostname":"oxz_propolis-server_1df2e802-2b61-4ae2-9ddf-2199e0196363","pid":21926,"dev":"chipset","register":"GpInputCtl","offset":0}
:156:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ Oct  6 15:15:04 Stopping because all processes in service exited. ]
[ Oct  6 15:15:04 Executing stop method (:kill). ]
```
From @gjcolombo: I suspect it's [this](https://github.com/oxidecomputer/omicron/blob/c03029373982a528d372c68f3015506f15dd2a07/common/src/api/external/error.rs#L378-L391) -- Propolis is returning Not Found (it'll do that if e.g. it's asked to change VM state when it doesn't think there's a running VM); sled agent [preserves that error](https://github.com/oxidecomputer/omicron/blob/c03029373982a528d372c68f3015506f15dd2a07/sled-agent/src/sled_agent.rs#L140-L159), then returns it to Omicron, where the aforementioned From impl sees that it's a client error and flattens it into a bad-request error.

The complex sled-agent and propolis logs are here:
catacomb:/data/staff/rack3/sled4-agent.log.tar.gz
catacomb:/data/staff/rack3/sled4-propolis_1df2e802.log

**Comment by gjcolombo** [comment]
The 404 here is by design (see #431)--Propolis is using it to indicate that someone has asked to perform an operation that requires an instance when no instance is active.

There's no instance active because this Propolis was started after the previous one panicked (and wasn't told to restart the instance). That probably isn't the behavior we want--we should leave the Propolis for dead and mark the instance as being in a bad state (and possibly consider restarting it, if its fault discipline says to do that). This is tracked by oxidecomputer/omicron#3209 (restart behavior) and oxidecomputer/omicron#3206 (panic detection).

The panic itself is the most concerning bit, but without a backtrace I'm not sure how easy it will be to figure out exactly what faulted (the panic is in a generic I/O routine that's used by many different callers). Unless there's a reason not to that I don't know about, I think we should reconfigure our service manifest or execution script to make sure the server runs with RUST_BACKTRACE=1 so that we know where the fault's coming from when this happens.

**Comment by pfmooney** [comment]
That propolis panic looks like oxidecomputer/propolis#520.  Which bits are we running here?

**Comment by askfongjojo** [comment]
Ah same thing. It's on the same Omicron commit as that customer's (4cf90f3d2bf89b29f12c1d2056a15cecd72cdba0) which predated your fix.

**Comment by askfongjojo** [comment]
@david-crespo - Can you please try deploying the instance in question ("ollama-test") on dogfood which has the fix for #520 and see if the issue is still reproducible there? Thanks.

**Comment by david-crespo** [comment]
Will do if still necessary, but check out what I just found in the Ollama install script where I locked up the Ubuntu instance:

https://github.com/jmorganca/ollama/blob/ab0668293cbfc2188b736d4c2b7dc0b7b997f5bf/scripts/install.sh#L111-L132

**Comment by askfongjojo** [comment]
Close as duplicate of #520
