### ISSUE TITLE
want pvpanic device

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#592]
It would be nice to emulate the [QEMU pvpanic device](https://www.qemu.org/docs/master/specs/pvpanic.html) so that if a VM has failed or is otherwise acting wonky, we can learn whether or not the guest has reported its own ill health.

I think the work here looks something like this (N.B. this is somewhat disorganized rambling, and some of it may not hold up as we begin to code):

- Decide what device interface to present to guests: this device can function as either an ISA bus device (with the guest indicating panic via port I/O) or a PCI device (in the PCI case we need to make sure to choose a device number that doesn't conflict with the space the `instance_ensure` endpoint implicitly reserves)
- Add an [instance spec](https://github.com/oxidecomputer/propolis/blob/85dc6db36709981c1d35b0651a18e20caee0b73f/crates/propolis-api-types/src/instance_spec/mod.rs) device type that Propolis servers can use to decide whether to add one of these devices to a new VM
  - Since we're still not live-migrating VMs yet, let alone between versions, it *should* be possible to add this directly to [`DeviceSpecV0`](https://github.com/oxidecomputer/propolis/blob/master/crates/propolis-api-types/src/instance_spec/v0/mod.rs#L110) without worrying about breaking anything. However, this is a good chance to reason about what would need to happen to safely make a change like this: we probably need the device to be optional and need to make sure serde doesn't serialize this field if the device doesn't exist.
- Decide how to get panic counts out of Propolis
  - This should probably be an Oximeter metric. Today, Propolis itself only produces [one metric](https://github.com/oxidecomputer/propolis/blob/85dc6db36709981c1d35b0651a18e20caee0b73f/bin/propolis-server/src/lib/stats.rs#L36-L43), and it's from the server itself and not from any of its entities. We'll probably want to do for other entities something similar to what we do for Crucible: pass a copy of the machine initializer's [producer registry](https://github.com/oxidecomputer/propolis/blob/85dc6db36709981c1d35b0651a18e20caee0b73f/bin/propolis-server/src/lib/initializer.rs#L121) to components that accept it and allow them to define their own producer and call `register_producer` on it.
  - For test purposes it might also be useful to be able to walk up to a Propolis server and ask for its guest panic count by defining a new, possibly test-only, endpoint that finds the pvpanic entity and figures out how many panics it has seen
- Write tests
  - If we do a PCI device, we can write a PHD test that verifies the device is listed by `lspci`
  - If we have a "how many panics have you seen?" endpoint, PHD can query it

**Comment by jclulow** [comment]
I'm surprised, but I suppose honestly not very much, that it doesn't offer any way to report a _panic string_.  One bit of information is not a very wide channel for communicating fault information!

**Comment by pfmooney** [comment]
As for what we expose to guests as part of the product, I'd be inclined to stick with the IO-port(/MMIO) implementation, so we aren't trying up a PCI device, should we need to add other things in the future.  Linux should still enumerate it, provided we tweak the ACPI tables accordingly.  (Which raises a separate question about how/when we might do that.)

That isn't to say that propolis-lib can't support both, if @hawkw feels like implementing them as part of the project.

**Comment by hawkw** [comment]
My initial thinking was that it would be nice to implement both the PCI and ISA IO port interfaces, because we don't necessarily know which interface a given guest will use? But, I'm open to being convinced otherwise...

**Comment by gjcolombo** [comment]
The Linux pvpanic-pci driver is a relatively recent addition (this [LKML review thread](https://lkml.iu.edu/hypermail/linux/kernel/2103.2/10209.html) is from 2021, so somewhere around 5.16?), and we have guest OSes in our support matrix that go further back than that, so we should definitely support the I/O port interface irrespective of what we tackle first/whether we also support PCI.
