### ISSUE TITLE
phd: multiline shell commands don't work with VT100 serial console backend

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#643]
PHD's `Vt80x24` terminal backend searches for strings by calling `termwiz::Surface::screen_chars_to_string()` and calling `rfind` on the result. This works fine for single-line search targets, but for multi-line targets, things are trickier, because `screen_chars_to_string` returns *entire lines* (including all their spaces) separated by `\n` characters. That is, if the virtual contents are

```
hello
world
user@host $
```

then a search for `hello\nworld` will not match, because `screen_chars_to_string` returns `hello`, then 75 spaces, then `\nworld`. PHD will need to account for this behavior when trying to watch for multiline strings.

**Comment by hawkw** [comment]
Bleh, that's...really annoying! Sorry for writing tests that depend on multiline shell commands! :P

**Comment by gjcolombo** [comment]
Don't sweat it--if anything I'm still mad that I haven't figured out how to get the relevant guests to behave themselves such that we could avoid having the VT100 backend in the first place...
