### ISSUE TITLE
propolis should allow for control over boot order

### ISSUE THREAD

**Issue by pfmooney** [oxidecomputer/propolis#697]
Placeholder issue relating to RFD 470 and oxidecomputer/customer-support#84

**Comment by pfmooney** [comment]
This should be easier to implement with once #705 is merged.

**Comment by iximeow** [comment]
we've got some limited control here as of https://github.com/oxidecomputer/propolis/pull/756, where you can now specify a list of  boot disks to `propolis-server`. Nexus then only ever records and provides a single boot disk. for the _why_s on the relatively limited implementation, i've added some more discussion to RFD 470.
