### ISSUE TITLE
Live Migration: Block Devices

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/propolis#84]
- [ ] "Detatch" message sent to Crucible
- [ ] Re-inflation of Crucible upstairs on target

May require additional interfacing with Propolis to define how "detatch" + state transfer works, but this issue tracks the transfer of Crucible Upstairs instances specifically.

**Comment by gjcolombo** [comment]
Migration of block devices is basically functional, but we don't implement Crucible deactivation/reactivation yet. Filed #365 to track that specifically.
